### ISSUE TITLE
"Cancel" button does not cancel

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/gitbase-web#241]
I run a "buggy" query which occupies 100% CPU for a long time:

```sql
SELECT files.repository_id, files.file_path,
    ARRAY_LENGTH(uast_extract(UAST(
        files.blob_content,
        LANGUAGE(files.file_path, files.blob_content),
        '//*[@roleFunction and @roleDeclaration]'),"token")
    ) as functions
FROM files NATURAL JOIN ref_commits as rc
WHERE rc.ref_name = 'HEAD' AND rc.history_index = 0
      AND LANGUAGE(files.file_path, files.blob_content) = 'Go'
ORDER BY functions DESC
```

I click the Cancel button, the robot breaks into pieces but gitbase continues to load 100% CPU.

**Comment by carlosms** [comment]
What is your browser and version?

**Comment by vmarkovtsev** [comment]
Chrome 69, version matches the latest Engine release.

**Comment by smola** [comment]
I think I'm hitting the same bug:
* browser: 62.0.2 (on Ubuntu Linux Bionic)
* gitbase: v0.17.0-rc.4
* gitbase-web: v0.1.5

My query, which was probably buggy, was:
```
FROM
	files AS f
WHERE
	LANGUAGE(f.file_path) = 'Java'
   	AND
    ARRAY_LENGTH(UAST_EXTRACT(UAST_CHILDREN(UAST_XPATH(UAST(f.blob_content, 'Java'), '//*[@roleFinally]')), '@type')) > 0
;
```

**Comment by carlosms** [comment]
The root cause is that the driver does not actually cancel the execution of the query, even though the docs say otherwise:
https://github.com/go-sql-driver/mysql/issues/863#issuecomment-426152037

The other popular mysql driver (https://github.com/ziutek/mymysql/releases) does not support cancellation, and last release was from 2015.

I think for now the only thing we can do is remove the cancel buttons, and later on investigate if we have any other option to make it work.

**Comment by smola** [comment]
@carlosms We might be able to use `SHOW FULL PROCESSLIST` and `KILL` to send a KILL to the right query.

**Comment by carlosms** [comment]
Yes, I was working on that on friday, and it's working fine. I didn't submit it yet because I need to work a bit more on the tests for it.

**Comment by pjebs** [comment]
This is my solution: https://medium.com/@rocketlaunchr.cloud/canceling-mysql-in-go-827ed8f83b30
