### ISSUE TITLE
CI: test go tip

### ISSUE THREAD

**Issue by dpordomingo** [src-d/gitbase-web#25]
We should configure the matrix for `tip` and `allow_failures` for that.

**Comment by bzz** [comment]
I would say that, as noted by @smacker in Slack, according to a proposal in https://github.com/src-d/guide/pull/220 - we might not  need this, for this application.

**Comment by smola** [comment]
We do not _support_ `tip`, but we can test it to catch issues in advance. @mcuadros argued that this is kind of pointless, since `allowed_failures` are not notified anywhere unless you check the interface.

So I would ask you as a team: do you check Travis UI itself? If you get a "silent" allowed failure, will you notice?

**Comment by smacker** [comment]
I personally not in 99% of cases. Just look at the status on Github.

**Comment by carlosms** [comment]
Same, I only go to Travis if GitHub says it's failing.

**Comment by bzz** [comment]
> If you get a "silent" allowed failure, will you notice?

never

**Comment by dpordomingo** [comment]
I'm **quite often** checking Travis.
I wonder if we could even configure something to add a message in the PR warning when tip fails -> what would help people not checking Travis.
